- name: Clean yum cache
  shell: "yum clean all"
  args:
    warn: no

- name: yum install sunrunim
  yum: name=sunrunim state=latest

- name: restart service openfire
  service:
    name: openfire
    state: restarted
    enabled: yes

- name: yum install sunrun-comm
  yum: name=sunrun-common-tools

- name: creat tables
  shell: /usr/local/bin/sunrun-sqlmigrate -s {{ sunrunim.mysql.host }} -P {{sunrunim.mysql.port}} -u {{ sunrunim.mysql.username }} -p {{ sunrunim.mysql.password }} -n openfire -d /usr/local/db/migrations/
  run_once: true
  ignore_errors: yes


#- name: config hazelcast
#  template: src=templates/hazelcast-local-config.xml.j2 dest=/opt/openfire/conf/hazelcast-local-config.xml
#  when: groups['openfires'] | length | int > 1

- name: start service openfire
  service:
    name: openfire
    state: started
    enabled: yes

- name: wait port 9090
  wait_for: port=9090 delay=2 timeout=15


- name: start service tomcat
  service:
    name: tomcat
    state: started
    enabled: yes

- name: wait port 8080
  wait_for: port=8080 delay=2 timeout=15

- name: Generate turn server list
  set_fact: turnserver_list="{{ turnserver_list }} + ['{{ hostvars[item].ansible_ssh_host }}']"
  with_items: "{{ groups['turnservers'] }}"

- name: create /etc/sunrunim
  file: path=/etc/sunrunim state=directory

- name: config tomcat ofProperty
  template: src=templates/ofProperty.properties.j2 dest=/etc/sunrunim/ofProperty.properties

- name: config tomcat jdbc
  template: src=templates/jdbc.properties.j2 dest=/etc/sunrunim/jdbc.properties

- name: stop service tomcat
  service:
    name: tomcat
    state: stopped
    enabled: yes

- name: start service tomcat
  service:
    name: tomcat
    state: started
    enabled: yes
